config/routes.rb
Underdogs::Application.routes.draw do
  resources :dogs do
    resources :items, :powers, :wounds
  end

  resources :forces do
    resources :dogs
  end

  resources :players do
    resources :forces do
      resources :dogs
    end
  end

  get "home/index"

  root :to => "home#index"

end

app/models/dog.rb
class Dog < ActiveRecord::Base
  belongs_to :force
  has_many :items
  has_many :powers
  has_many :wounds
end

app/models/force.rb
class Force < ActiveRecord::Base
  belongs_to :player
  has_many :dogs
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :dog
end

app/models/player.rb
class Player < ActiveRecord::Base
  has_many :forces
  has_many :dogs, :through => :forces
end

app/models/power.rb
class Power < ActiveRecord::Base
  belongs_to :dog
end

app/models/wound.rb
class Wound < ActiveRecord::Base
  belongs_to :dog
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  # GET /dogs
  # GET /dogs.xml
  def index
    @dogs = Dog.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @dogs }
    end
  end

  # GET /dogs/1
  # GET /dogs/1.xml
  def show
    @dog = Dog.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @dog }
    end
  end

  # GET /dogs/new
  # GET /dogs/new.xml
  def new
    @dog = Dog.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @dog }
    end
  end

  # GET /dogs/1/edit
  def edit
    @dog = Dog.find(params[:id])
  end

  # POST /dogs
  # POST /dogs.xml
  def create
    @force = Force.find(params[:force_id])
    @dog = @force.dogs.create(params[:dog])
    redirect_to force_path(@force)
  end

  # PUT /dogs/1
  # PUT /dogs/1.xml
  def update
    @dog = Dog.find(params[:id])

    respond_to do |format|
      if @dog.update_attributes(params[:dog])
        format.html { redirect_to(@dog, :notice => 'Dog was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @dog.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /dogs/1
  # DELETE /dogs/1.xml
  def destroy
    @dog = Dog.find(params[:id])
    @dog.destroy

    respond_to do |format|
      format.html { redirect_to(dogs_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/forces_controller.rb
class ForcesController < ApplicationController
  # GET /forces
  # GET /forces.xml
  def index
    @forces = Force.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @forces }
    end
  end

  # GET /forces/1
  # GET /forces/1.xml
  def show
    @force = Force.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @force }
    end
  end

  # GET /forces/new
  # GET /forces/new.xml
  def new
    @force = Force.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @force }
    end
  end

  # GET /forces/1/edit
  def edit
    @force = Force.find(params[:id])
  end

  # POST /forces
  # POST /forces.xml
  def create
    @player = Player.find(params[:player_id])
    @force = @player.forces.create(params[:force])
    redirect_to player_path(@player)
  end

  # PUT /forces/1
  # PUT /forces/1.xml
  def update
    @force = Force.find(params[:id])

    respond_to do |format|
      if @force.update_attributes(params[:force])
        format.html { redirect_to(@force, :notice => 'Force was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @force.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /forces/1
  # DELETE /forces/1.xml
  def destroy
    @force = Force.find(params[:id])
    @force.destroy

    respond_to do |format|
      format.html { redirect_to(forces_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  @dog = Dog.find(params[:dog_id])
  @item = @dog.items.create(params[:item])
  redirect_to edit_dog_path(@dog)
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  # GET /players
  # GET /players.xml
  def index
    @players = Player.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @players }
    end
  end

  # GET /players/1
  # GET /players/1.xml
  def show
    @player = Player.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @player }
    end
  end

  # GET /players/new
  # GET /players/new.xml
  def new
    @player = Player.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @player }
    end
  end

  # GET /players/1/edit
  def edit
    @player = Player.find(params[:id])
  end

  # POST /players
  # POST /players.xml
  def create
    @player = Player.new(params[:player])

    respond_to do |format|
      if @player.save
        format.html { redirect_to(@player, :notice => 'Player was successfully created.') }
        format.xml  { render :xml => @player, :status => :created, :location => @player }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @player.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /players/1
  # PUT /players/1.xml
  def update
    @player = Player.find(params[:id])

    respond_to do |format|
      if @player.update_attributes(params[:player])
        format.html { redirect_to(@player, :notice => 'Player was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @player.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.xml
  def destroy
    @player = Player.find(params[:id])
    @player.destroy

    respond_to do |format|
      format.html { redirect_to(players_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/powers_controller.rb
class PowersController < ApplicationController
  @dog = Dog.find(params[:dog_id])
  @power = @dog.powers.create(params[:power])
  redirect_to edit_dog_path(@dog)
end

app/controllers/wounds_controller.rb
class WoundsController < ApplicationController
  @dog = Dog.find(params[:dog_id])
  @wound = @dog.wounds.create(params[:wound])
  redirect_to edit_dog_path(@dog)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/forces_helper.rb
module ForcesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/powers_helper.rb
module PowersHelper
end

app/helpers/wounds_helper.rb
module WoundsHelper
end

app/views/dogs/edit.html.erb
<head>
  <link rel="stylesheet" type="text/css" href="http://www.lars-san.com/war40k/underdogs/war-under.css" />

	<script language='JavaScript'>
	Current = "0";
	WSlevel = <%= @dog.WS %>;
	function display()
	  {
	  document.testing.Display.value = Current;
	  }
	function Increase(stat)
	  {
	  WSlevel++;
	  document.getElementById('hero-'+stat).innerHTML = WSlevel;
	  }
	function sayHello()
	  {
	  document.getElementById('hello').innerHTML = Current;//This is a check to make sure basic Javasscript is working on the page. It will be removed when the page goes live.
	  Current = document.getElementById('hero-name').innerHTML;
	  WSlevel = document.getElementById('hero-WS').innerHTML;
	  }
	window.onload = sayHello;
	</script>
</head>
<p id="notice"><%= notice %></p>
<h1>Editting <%= @dog.name %></h1>
<p id="hello"></p><!-- This is a check to make sure basic Javasscript is working on the page. It will be removed when the page goes live. -->

<div id="content">
<!-- This section is not needed when only listing a single hero.
<div id="section">
	<h2><u><b>Units</b></u></h2>
</div>
-->
<!-- This section is not needed when only listing a single hero. It will be used when listing many from different armies as the seperator between the armies, labeling them.
<div id="name">
	<a name="hq"></a>
	<h2>HQ</h2>
</div>
-->
<div id="rulesbox">
	<div id="name">
		<a name="archon"></a>
		<font size="+2"><%= @dog.name %></font>
	</div>
	<div id="points">
		<font size="-1">Total: Javascript goes here New: <%= @dog.newpoints %> Used: <%= @dog.usedpoints %></font>
	</div>
	<div id="rulesbox-left">
		<div id="rulesbox-stats">
			<table><tr><td width="150"></td><td width="25"><center><b>WS</b></center></td><td width="25"><center><b>BS</b></center></td><td width="25"><center><b>S</b></center></td><td width="25"><center><b>T</b></center></td><td width="25"><center><b>W</b></center></td><td width="25"><center><b>I</b></center></td><td width="25"><center><b>A</b></center></td><td width="25"><center><b>Ld</b></center></td><td width="25"><center><b>Sv</b></center></td></tr>
				<tr><td><%= @dog.name %></td><!-- Name -->
				<td><center><%= @dog.WS %></center></td><!-- WS -->
				<td><center><%= @dog.BS %></center></td><!-- BS -->
				<td><center><%= @dog.S %></center></td><!-- S -->
				<td><center><%= @dog.T %></center></td><!-- T -->
				<td><center><%= @dog.W %></center></td><!-- W -->
				<td><center><%= @dog.I %></center></td><!-- I -->
				<td><center><%= @dog.A %></center></td><!-- A -->
				<td><center><%= @dog.Ld %></center></td><!-- Ld -->
				<td><center><%= @dog.Sv %><font size="-2">+</font></center></td><!-- Sv -->
			</tr>
			<tr>
				<td><span align="center">Increase</span></td>
			</tr></table>
		</div>
		<div id="rulesbox-leftleft">
			<div id="rulesbox-float">
				<b>Unit Type:</b><br />
				&bull; Infantry
			</div>
			<div id="rulesbox-float">
				<b>Unit/squad:</b><br />
				&bull; <%= @dog.unit %>
			</div>
			<div id="rulesbox-float">
				<b>Wargear:</b><br />
				<% @dog.items.each do |item| %>
				&bull; <%= item.name %> <font color="grey" size="-1"><% if item.points != 0 %><%= item.points %> points<% end %></font><!-- The ruby code inside the font tag will make any point value other than '0' be displayed. -->
				<%= link_to 'X', dog_item_path(@dog, item), :confirm => 'Are you sure?', :method => :delete %><br />
				<% end %>
				Add Wargear:<br />
				<%= form_for([@dog, @dog.items.build]) do |f| %>
					<%= f.text_field :name %>
					<%= f.label :points %><br />
					<%= f.text_field :points %>
					<%= f.submit %>
				<% end %>
			</div>
		</div>
		<div id="rulesbox-leftright">
			<div id="rulesbox-float">
				<b>Special Rules:</b><br />
				<% @dog.powers.each do |power| %>
				&bull; <%= power.name %> <%= link_to 'X', dog_power_path(@dog, power), :confirm => 'Are you sure?', :method => :delete %><br />
				<% end %>
				Add Ability:<br />
				<%= form_for([@dog, @dog.powers.build]) do |f| %>
					<%= f.text_field :name %>
					<%= f.submit %>
				<% end %>
			</div>
		</div>
	</div>
	<div id="rulesbox-right">
		<b>Background:</b><br />
		<%= @dog.background %><br /><br />
		<% if @dog.wounds.count != 0 %>
			<b>Injuries:</b><br />
			<% @dog.wounds.each do |wound| %>
			&bull; <%= wound.created_at %> <%= wound.details %><br />
			<% end %>
		<% end %>
		<% if @dog.wounds.empty? %>
			<b>No Injuries</b><br />
		<% end %>
		Add Injury:<br />
		<%= form_for([@dog, @dog.wounds.build]) do |f| %>
			<%= f.text_area :details %>
			<%= f.submit %>
		<% end %>
		<%= link_to 'Show', dog_path(@dog) %><br />
		<%= link_to 'Destroy', @dog, :confirm => 'Are you sure?', :method => :delete %>
	</div>
</div>

<div id="section">
--Old section--<br />
<%= render 'form' %>

<%= link_to 'Show', @dog %> |
<%= link_to 'Back', dogs_path %>
</div>
</div>

app/views/dogs/index.html.erb
<h1>Listing dogs</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Unit</th>
    <th>Rank</th>
    <th>Ws</th>
    <th>Bs</th>
    <th>S</th>
    <th>T</th>
    <th>W</th>
    <th>I</th>
    <th>A</th>
    <th>Ld</th>
    <th>Sv</th>
    <th>Newpoints</th>
    <th>Usedpoints</th>
    <th>Ows</th>
    <th>Obs</th>
    <th>Os</th>
    <th>Ot</th>
    <th>Ow</th>
    <th>Oi</th>
    <th>Oa</th>
    <th>Old</th>
    <th>Modelcost</th>
    <th>Background</th>
    <th>Force</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @dogs.each do |dog| %>
  <tr>
    <td><%= dog.name %></td>
    <td><%= dog.unit %></td>
    <td><%= dog.rank %></td>
    <td><%= dog.WS %></td>
    <td><%= dog.BS %></td>
    <td><%= dog.S %></td>
    <td><%= dog.T %></td>
    <td><%= dog.W %></td>
    <td><%= dog.I %></td>
    <td><%= dog.A %></td>
    <td><%= dog.Ld %></td>
    <td><%= dog.Sv %></td>
    <td><%= dog.newpoints %></td>
    <td><%= dog.usedpoints %></td>
    <td><%= dog.oWS %></td>
    <td><%= dog.oBS %></td>
    <td><%= dog.oS %></td>
    <td><%= dog.oT %></td>
    <td><%= dog.oW %></td>
    <td><%= dog.oI %></td>
    <td><%= dog.oA %></td>
    <td><%= dog.oLd %></td>
    <td><%= dog.modelcost %></td>
    <td><%= dog.background %></td>
    <td><%= dog.force %></td>
    <td><%= link_to 'Show', dog %></td>
    <td><%= link_to 'Edit', edit_dog_path(dog) %></td>
    <td><%= link_to 'Destroy', dog, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Dog', new_dog_path %>

app/views/dogs/new.html.erb
<h1>New dog</h1>

<%= render 'form' %>

<%= link_to 'Back', dogs_path %>

app/views/dogs/old-edit.html.erb
<h1>Editing dog</h1>

<%= render 'form' %>

<%= link_to 'Show', @dog %> |
<%= link_to 'Back', dogs_path %>

app/views/dogs/old-new.html.erb
<h1>New dog</h1>

<%= render 'form' %>

<%= link_to 'Back', dogs_path %>

app/views/dogs/old-show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @dog.name %>
</p>

<p>
  <b>Unit:</b>
  <%= @dog.unit %>
</p>

<p>
  <b>Rank:</b>
  <%= @dog.rank %>
</p>

<p>
  <b>Ws:</b>
  <%= @dog.WS %>
</p>

<p>
  <b>Bs:</b>
  <%= @dog.BS %>
</p>

<p>
  <b>S:</b>
  <%= @dog.S %>
</p>

<p>
  <b>T:</b>
  <%= @dog.T %>
</p>

<p>
  <b>W:</b>
  <%= @dog.W %>
</p>

<p>
  <b>I:</b>
  <%= @dog.I %>
</p>

<p>
  <b>A:</b>
  <%= @dog.A %>
</p>

<p>
  <b>Ld:</b>
  <%= @dog.Ld %>
</p>

<p>
  <b>Sv:</b>
  <%= @dog.Sv %>
</p>

<p>
  <b>Newpoints:</b>
  <%= @dog.newpoints %>
</p>

<p>
  <b>Usedpoints:</b>
  <%= @dog.usedpoints %>
</p>

<p>
  <b>Ows:</b>
  <%= @dog.oWS %>
</p>

<p>
  <b>Obs:</b>
  <%= @dog.oBS %>
</p>

<p>
  <b>Os:</b>
  <%= @dog.oS %>
</p>

<p>
  <b>Ot:</b>
  <%= @dog.oT %>
</p>

<p>
  <b>Ow:</b>
  <%= @dog.oW %>
</p>

<p>
  <b>Oi:</b>
  <%= @dog.oI %>
</p>

<p>
  <b>Oa:</b>
  <%= @dog.oA %>
</p>

<p>
  <b>Old:</b>
  <%= @dog.oLd %>
</p>

<p>
  <b>Modelcost:</b>
  <%= @dog.modelcost %>
</p>

<p>
  <b>Background:</b>
  <%= @dog.background %>
</p>

<p>
  <b>Force:</b>
  <%= @dog.force %>
</p>


<%= link_to 'Edit', edit_dog_path(@dog) %> |
<%= link_to 'Back', dogs_path %>

app/views/dogs/show.html.erb
<head>
  <link rel="stylesheet" type="text/css" href="http://www.lars-san.com/war40k/underdogs/war-under.css" />
</head>
<p id="notice"><%= notice %></p>
<h1><%= @dog.name %></h1>

<div id="content">
<!-- This section is not needed when only listing a single hero.
<div id="section">
	<h2><u><b>Units</b></u></h2>
</div>
-->
<!-- This section is not needed when only listing a single hero. It will be used when listing many from different armies as the seperator between the armies, labeling them.
<div id="name">
	<a name="hq"></a>
	<h2>HQ</h2>
</div>
-->
<div id="rulesbox">
	<div id="name">
		<a name="archon"></a>
		<font size="+2"><%= @dog.name %></font>
	</div>
	<div id="points">
		<font size="-1">Total: Javascript goes here New: <%= @dog.newpoints %> Used: <%= @dog.usedpoints %></font>
	</div>
	<div id="rulesbox-left">
		<div id="rulesbox-stats">
			<table><tr><td width="150"></td><td width="25"><center><b>WS</b></center></td><td width="25"><center><b>BS</b></center></td><td width="25"><center><b>S</b></center></td><td width="25"><center><b>T</b></center></td><td width="25"><center><b>W</b></center></td><td width="25"><center><b>I</b></center></td><td width="25"><center><b>A</b></center></td><td width="25"><center><b>Ld</b></center></td><td width="25"><center><b>Sv</b></center></td></tr>
				<tr><td><%= @dog.name %></td><!-- Name -->
				<td><center><%= @dog.WS %></center></td><!-- WS -->
				<td><center><%= @dog.BS %></center></td><!-- BS -->
				<td><center><%= @dog.S %></center></td><!-- S -->
				<td><center><%= @dog.T %></center></td><!-- T -->
				<td><center><%= @dog.W %></center></td><!-- W -->
				<td><center><%= @dog.I %></center></td><!-- I -->
				<td><center><%= @dog.A %></center></td><!-- A -->
				<td><center><%= @dog.Ld %></center></td><!-- Ld -->
				<td><center><%= @dog.Sv %><font size="-2">+</font></center></td><!-- Sv -->
			</tr></table>
		</div>
		<div id="rulesbox-leftleft">
			<div id="rulesbox-float">
				<b>Unit Type:</b><br />
				&bull; Infantry
			</div>
			<div id="rulesbox-float">
				<b>Unit/squad:</b><br />
				&bull; <%= @dog.unit %>
			</div>
			<div id="rulesbox-float">
				<b>Wargear:</b><br />
				<% @dog.items.each do |item| %>
				&bull; <%= item.name %> <font color="grey" size="-1"><% if item.points != 0 %><%= item.points %> points<% end %></font><br /><!-- The ruby code inside the font tag will make any point value other than '0' be displayed. -->
				<% end %>
			</div>
		</div>
		<div id="rulesbox-leftright">
			<div id="rulesbox-float">
				<b>Special Rules:</b><br />
				<% @dog.powers.each do |power| %>
				&bull; <%= power.name %><br />
				<% end %>
			</div>
		</div>
	</div>
	<div id="rulesbox-right">
		<b>Background:</b><br />
		<%= @dog.background %><br /><br />
		<% if @dog.wounds.count != 0 %>
			<b>Injuries:</b><br />
			<% @dog.wounds.each do |wound| %>
			&bull; <%= wound.created_at %> <% if wound.details != '' %><%= wound.details %> points<% end %><br /><!-- The ruby code inside the font tag will make any point value other than '0' be displayed. -->
			<% end %>
		<% end %>
		<% if @dog.wounds.empty? %>
			<b>No Injuries</b><br />
		<% end %>
		<%= link_to 'Edit', edit_dog_path(@dog) %><br />
		<%= link_to 'Destroy', @dog, :confirm => 'Are you sure?', :method => :delete %>
	</div>
</div>

<div id="name">
--Misc stats--<br />
<p>
  <b>Newpoints:</b>
  <%= @dog.newpoints %>
</p>

<p>
  <b>Usedpoints:</b>
  <%= @dog.usedpoints %>
</p>

<p>
  <b>Model cost:</b>
  <%= @dog.modelcost %>
</p>

<p>
  <b>Base WS:</b>
  <%= @dog.oWS %>
</p>

<p>
  <b>Base BS:</b>
  <%= @dog.oBS %>
</p>

<p>
  <b>Base S:</b>
  <%= @dog.oS %>
</p>

<p>
  <b>Base T:</b>
  <%= @dog.oT %>
</p>

<p>
  <b>Base W:</b>
  <%= @dog.oW %>
</p>

<p>
  <b>Base I:</b>
  <%= @dog.oI %>
</p>

<p>
  <b>Base A:</b>
  <%= @dog.oA %>
</p>

<p>
  <b>Base Ld:</b>
  <%= @dog.oLd %>
</p>

<h2>Add Wargear:</h2>
<%= form_for([@dog, @dog.items.build]) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :points %><br />
    <%= f.text_field :points %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<h2>Add Special Ability:</h2>
<%= form_for([@dog, @dog.powers.build]) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<h2>Add Injury Information:</h2>
<%= form_for([@dog, @dog.wounds.build]) do |f| %>
  <div class="field">
    <%= f.label :details %><br />
    <%= f.text_area :details %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Edit', edit_dog_path(@dog) %> |
<%= link_to 'Back', dogs_path %>
</div>

</div>

app/views/forces/edit.html.erb
<h1>Editing force</h1>

<%= render 'form' %>

<h2>List of Heroes</h2>
<% @force.dogs.each do |dog| %>
  <p>
    <b>Name:</b>
    <%= link_to dog.name, dog_path(dog) %>
  </p>
<% end %>
 
<h2>Add a Hero:</h2>
<%= form_for([@force, @force.dogs.build]) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :backstory %><br />
    <%= f.text_area :background %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Show', @force %> |
<%= link_to 'Back', forces_path %>

app/views/forces/index.html.erb
<h1>Listing forces</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Race</th>
    <th>Player</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @forces.each do |force| %>
  <tr>
    <td><%= force.name %></td>
    <td><%= force.race %></td>
    <td><%= force.player %></td>
    <td><%= link_to 'Show', force %></td>
    <td><%= link_to 'Edit', edit_force_path(force) %></td>
    <td><%= link_to 'Destroy', force, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Force', new_force_path %>

app/views/forces/new.html.erb
<h1>New force</h1>

<%= render 'form' %>

<%= link_to 'Back', forces_path %>

app/views/forces/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @force.name %>
</p>

<p>
  <b>Race:</b>
  <%= @force.race %>
</p>

<h2>List of Heroes</h2>
<% @force.dogs.each do |dog| %>
  <p>
    <b>Name:</b>
    <%= link_to dog.name, dog_path(dog) %>
  </p>
<% end %>

<%= link_to 'Edit', edit_force_path(@force) %> |
<%= link_to 'Back', forces_path %>

app/views/home/index.html.erb
<h1>Underdogs Campaign</h1>

<p><%= link_to "Players", players_path %></p>
<p><%= link_to "Armies", forces_path %></p>
<p><%= link_to "Heroes", dogs_path %></p>
<h2>Home#index</h2>
<p>Find me in app/views/home/index.html.erb</p>

app/views/players/edit.html.erb
<h1>Editing player</h1>

<%= render 'form' %>

<h2>List of Armies</h2>
<% @player.forces.each do |force| %>
  <p>
    <b>Name:</b>
    <%= force.name %>
  </p>
 
  <p>
    <b>Type:</b>
    <%= force.race %>
  </p>
<%= link_to 'Show', force_path(force) %>
<% end %>
 
<h2>Add an Army:</h2>
<%= form_for([@player, @player.forces.build]) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :type %><br />
    <%= f.text_area :race %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<h1>Listing players</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @players.each do |player| %>
  <tr>
    <td><%= player.name %></td>
    <td><%= link_to 'Show', player %></td>
    <td><%= link_to 'Edit', edit_player_path(player) %></td>
    <td><%= link_to 'Destroy', player, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Player', new_player_path %>

app/views/players/new.html.erb
<h1>New player</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @player.name %>
</p>

<h2>List of Armies</h2>
<% @player.forces.each do |force| %>
  <p>
    <b>Name:</b>
    <%= link_to force.name, force_path(force) %>
  </p>
 
  <p>
    <b>Type:</b>
    <%= force.race %>
  </p>
<% end %>

<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>